### ISSUE TITLE
Duplicate declaration warnings on dashboard

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKSphinxExamples#266]
The `Linux Examples Documentation` build of the Insight dashboard:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7112107

is signalling duplicate declaration warnings for the classes that are marked as being demonstrated in each example's `Documentation.rst` file with the `.. breathelink:: ` tag:
e.g.
```
[CTest: warning matched]
/home/kitware/Dashboards/Tests/ITKExamples-doc-build/ITKEx-buildCore/Common/
BuildAHelloWorldProgram/Documentation.rst:102:
WARNING: Duplicate declaration,
template<typename TPixel, unsigned int VImageDimension = 2> itk::Image :
public itk::ImageBase< VImageDimension >
```

Not sure why this is being reported. Also, the build seems not to trigger nightly (or it might take a long time to build), and hence the reporting frequency is not consistent.

**Comment by dzenanz** [comment]
I think this was resolved meanwhile. Can you confirm Jon?

**Comment by jhlegarreta** [comment]
> I think this was resolved meanwhile. Can you confirm Jon?

I am unable to find recent builds in the dashboard, even going a few days back. So I cannot confirm. But if you feel confident that it has been resolved, please close the issue :+1:.

Thanks for the effort @dzenanz.

**Comment by dzenanz** [comment]
What kind of build are you looking for? Does today's [CI build](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/runs/4644062009?check_suite_focus=true) or its [dashboard](https://open.cdash.org/build/7646735) work?

**Comment by jhlegarreta** [comment]
I was looking at the dashboard regular builds, as the issue report build seemed a regular build that was reporting about the examples documentation builds.

**Comment by tbirdso** [comment]
This issue is still observed. Updating to Sphinx 4.4.0 changed the error message slightly:
> [ITKEx-build/src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Documentation.rst:131](https://github.com/InsightSoftwareConsortium/ITK/blob/master/ITKEx-build/src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Documentation.rst#L131): WARNING: Duplicate C++ declaration, also defined at src/Bridge/VtkGlue/ConvertAnRGBitkImageTovtkImageData/Documentation:129.

Please see #324 for additional investigation notes to date. 50 warnings about duplicate declarations in `breathelink`s are blocking CI from publishing updating docs.

**Comment by thewtex** [comment]
@tbirdso thanks for the detailed investigation!

It sounds like we should exclude the warnings here:

https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/7c7f794634df774c9b3ee291c598422dc727960c/CMake/CTestCustom.cmake.in#L37-L85
